apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-forge-controller
  namespace: frontend-forge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-forge-controller
rules:
  - apiGroups: ["frontend-forge.io"]
    resources: ["frontendintegrations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["frontend-forge.io"]
    resources: ["frontendintegrations/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["extensions.kubesphere.io"]
    resources: ["jsbundles"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frontend-forge-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frontend-forge-controller
subjects:
  - kind: ServiceAccount
    name: frontend-forge-controller
    namespace: frontend-forge-system
