apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-forge-runner
  namespace: extension-frontend-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-forge-runner-fi-reader
rules:
  - apiGroups: ["frontend-forge.io"]
    resources: ["frontendintegrations"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frontend-forge-runner-fi-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frontend-forge-runner-fi-reader
subjects:
  - kind: ServiceAccount
    name: frontend-forge-runner
    namespace: extension-frontend-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-forge-runner-config-writer
  namespace: extension-frontend-forge
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-forge-runner-config-writer
  namespace: extension-frontend-forge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend-forge-runner-config-writer
subjects:
  - kind: ServiceAccount
    name: frontend-forge-runner
    namespace: extension-frontend-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontend-forge-runner-jsbundle-writer
rules:
  - apiGroups: ["extensions.kubesphere.io"]
    resources: ["jsbundles"]
    verbs: ["get", "create", "patch", "update"]
  - apiGroups: ["extensions.kubesphere.io"]
    resources: ["jsbundles/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frontend-forge-runner-jsbundle-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frontend-forge-runner-jsbundle-writer
subjects:
  - kind: ServiceAccount
    name: frontend-forge-runner
    namespace: extension-frontend-forge
