apiVersion: frontend-forge.io/v1alpha1
kind: FrontendIntegration
metadata:
  name: demo-fi
  namespace: default
  annotations:
    kubesphere.io/description: Demo iframe integration
spec:
  displayName: Demo FI
  enabled: true
  builder:
    engineVersion: v1
  integration:
    type: iframe
    iframe:
      src: http://example.test/frontend
  routing:
    path: demo
  menu:
    placements:
      - global
      - workspace
