[package]
name = "frontend-forge-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
